# Generated by Django 2.2.9 on 2020-03-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_user'),
        ('users', '0002_auto_20200320_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user', to='home.CustomText'),
        ),
    ]
