# Generated by Django 2.2.9 on 2020-03-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_customtext_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="test",),
        migrations.RemoveField(model_name="customtext", name="tests",),
        migrations.AddField(
            model_name="customtext",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_home",
                to="home.HomePage",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customtext",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
