# Generated by Django 2.2.9 on 2020-03-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200322_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='home2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_home2', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='customtext',
            name='home3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_home3', to='home.HomePage'),
        ),
    ]
