# Generated by Django 2.2.9 on 2020-03-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0006_auto_20200322_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
